name: flutter_cv
description: use `ffi` to build opencv-flutter tools

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  native_opencv_windows:
    path: ../windows_opencv
  tuple: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
